spring.application.name=8th-BE-Blog

# No database is used in this assignment. Remove this exclusion when configuring MySQL.
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
