spring.application.name=8th-BE-Blog
# Week 1 does not use a database. Remove this exclusion when configuring MySQL.
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
